version: '4'
services:
  frontend:
    build: ./frontend
    container_name: frontend-react
    ports:
      - "5173:80"


  backend:
    build: ./API
    container_name: backend-express
    ports:
      - "8800:8800"
